<center>
    <h1>JaxTon</h1>
    <i>💯 JAX exercises</i>
    <br>
    <br>
    <a href='https://github.com/vopani/jaxton/blob/master/LICENSE'>
        <img src='https://img.shields.io/badge/license-Apache%202.0-blue.svg?logo=apache'>
    </a>
    <a href='https://github.com/vopani/jaxton'>
        <img src='https://img.shields.io/github/stars/vopani/jaxton?color=yellowgreen&logo=github'>
    </a>
    <a href='https://twitter.com/vopani'>
        <img src='https://img.shields.io/twitter/follow/vopani'>
    </a>
</center>

<center>
    This is Set 1: JAX Introduction (Exercises 1-10) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>

**Prerequisites**

* The configuration of jax should be updated as shown in the code snippet below in order to use TPUs

In [1]:
## install jax
!python3 -m pip install jax

In [2]:
## import packages
import jax
import os
import requests

## setup JAX to use TPUs if available
try:
    url = 'http:' + os.environ['TPU_NAME'].split(':')[1] + ':8475/requestversion/tpu_driver_nightly'
    resp = requests.post(url)
    jax.config.FLAGS.jax_xla_backend = 'tpu_driver'
    jax.config.FLAGS.jax_backend_target = os.environ['TPU_NAME']
except:
    pass

jax.devices()

[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0),
 TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1),
 TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0),
 TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1),
 TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0),
 TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1),
 TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0),
 TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]

**Exercise 1: Install the `jax` package**

In [3]:
!pip install jax

**Exercise 2: Import the `jax` package**

In [4]:
import jax

**Exercise 3: Display the version of `jax`**

In [5]:
jax.__version__

'0.2.25'

**Exercise 4: Display the default backend of `jax`**

In [6]:
jax.default_backend()

'tpu'

**Exercise 5: Display the devices of the backend**

In [7]:
jax.devices()

[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0),
 TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1),
 TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0),
 TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1),
 TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0),
 TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1),
 TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0),
 TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]

**Exercise 6: Create a JAX DeviceArray with values [10, 1, 24] and assign it to `data`**

In [8]:
data = jax.numpy.array([10, 1, 24])
data

DeviceArray([10,  1, 24], dtype=int32)

**Exercise 7: Display the type of `data`**

In [9]:
type(data)

jax.interpreters.xla._DeviceArray

**Exercise 8: Display the shape of `data`**

In [10]:
data.shape

(3,)

**Exercise 9: Transfer `data` to host and assign it to `data_host`**

In [11]:
data_host = jax.device_get(data)
data_host

array([10,  1, 24], dtype=int32)

**Exercise 10: Transfer `data_host` to device and assign it to `data_device`**

In [12]:
data_device = jax.device_put(data_host)
data_device

DeviceArray([10,  1, 24], dtype=int32)

✅ This completes Set 1: JAX Introduction (Exercises 1-10) of **JaxTon**: *💯 JAX exercises*

You can find all the exercises and solutions on [GitHub](https://github.com/vopani/jaxton#exercises-)